version: 1.1.{build}
image: Visual Studio 2017

environment:
  CYG_ROOT: C:\cygwin64

build_script:
  - '%CYG_ROOT%/bin/bash -lc "$APPVEYOR_BUILD_FOLDER/scripts/build.sh"'
test_script:
  - '%CYG_ROOT%/bin/bash -lc "$APPVEYOR_BUILD_FOLDER/scripts/runTests.sh"'