version: 1.1.0.{build}
image: Visual Studio 2017

environment:
  CYG_ROOT: C:\cygwin64

build_script:
  - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./scripts/build.sh"'
test_script:
  - '%CYG_ROOT%/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER; ./scripts/runTests.sh"'